'use strict'
const fs = require('fs')
const path = require('path')
const { verifyRelease } = require('./release-integrity')
const root = path.resolve(__dirname, '..')
const relative = process.env.DPA_DIST_DIR || 'dist'
const unpacked = path.join(root, relative, 'win-unpacked')
const exe = path.join(unpacked, 'DeepSeek-PA.exe')
const asar = path.join(unpacked, 'resources', 'app.asar')
const release = path.join(root, relative, 'release.json')
for (const file of [exe, asar, release]) if (!fs.existsSync(file)) throw new Error('正式发布产物缺失：' + file)
if (fs.existsSync(path.join(root, 'dist-rebuilt'))) throw new Error('检测到旧版 dist-rebuilt，请先执行 npm run publish:desktop')
if (fs.existsSync(path.join(root, 'dist-staging'))) throw new Error('检测到未发布的 dist-staging，请先执行 npm run publish:desktop')
const result = verifyRelease(root, path.join(root, relative), { requireMetadata: true })
console.log('DPA desktop package verified:', result.version, Object.keys(result.files).length, 'files', result.archiveSha256)
